### ISSUE TITLE
DealerHits eternally

### ISSUE THREAD

**Issue by tphxlly** [CampbellWest/Sec2-Group1-TBS#3]
After the player has chosen to stand, the dealer never stops drawing cards.

Possible issue with Draw() function.

**Comment by penfieldCui** [comment]
#3 fixed by passing pointer.

**Comment by CampbellWest** [comment]
Originally found in dealerHits.c on line 10, the draw() function would be called and would never properly hit a card. After debugging the issue was found to be calling draw(&dealer, &deck, ...). Because the address of the deck and dealer was already passed into dealerHits(), we didn't have to passed it again into draw. Changing the call to draw(dealer, deck, ...) inside dealerHits() fixed this problem.
